name: Check the source code
on:
 push:
  branches:
   - develop
 pull_request:
  branches:
   - develop
jobs:
 test:
  name: Check the source code
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.16.9'
      channel: 'stable'
   - name: Create .env file
     run: echo "USE_DEBUG_MODE=${{ secrets.USE_DEBUG_MODE }}" >> .env
          && echo "PGN_API_BASE_URL=${{ secrets.PGN_API_BASE_URL }}" >> .env
          && echo "MASTODON_CLIENT_ID=\${{ secrets.MASTODON_CLIENT_ID }}" >> .env
          && echo "MASTODON_CLIENT_SECRET=\${{ secrets.MASTODON_CLIENT_SECRET }}" >> .env
          && echo "MASTODON_REDIRECT_URI=\${{ secrets.MASTODON_REDIRECT_URI }}" >> .env
          && echo "MASTODON_INSTANCE_URL=\${{ secrets.MASTODON_INSTANCE_URL }}" >> .env

   #   run: echo "FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}" >> .env
   #        && echo "FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}" >> .env
   #        && echo "FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}" >> .env
   #        && echo "FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}" >> .env
   #        && echo "FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }}" >> .env
   #        && echo "FIREBASE_APP_ID_IOS=${{ secrets.FIREBASE_APP_ID_IOS }}" >> .env
   #        && echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
   - name: Install packages
     run: flutter pub get
   - name: Run the code generator
     run: flutter pub run build_runner build
   - name: Linter
     run: flutter analyze
   - name: Test
     run: flutter test test
